// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Roster.proto

package com.jeson.roster.proto;

public final class Roster {
    private Roster() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface StudentOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Student)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required int32 id = 1;</code>
         */
        boolean hasId();

        /**
         * <code>required int32 id = 1;</code>
         */
        int getId();

        /**
         * <code>required string name = 2;</code>
         */
        boolean hasName();

        /**
         * <code>required string name = 2;</code>
         */
        java.lang.String getName();

        /**
         * <code>required string name = 2;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>required .Student.Sex sex = 3;</code>
         */
        boolean hasSex();

        /**
         * <code>required .Student.Sex sex = 3;</code>
         */
        com.jeson.roster.proto.Roster.Student.Sex getSex();
    }

    /**
     * Protobuf type {@code Student}
     */
    public static final class Student extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:Student)
            StudentOrBuilder {
        // Use Student.newBuilder() to construct.
        private Student(com.google.protobuf.GeneratedMessage.Builder builder) {
            super(builder);
        }

        private Student() {
            id_ = 0;
            name_ = "";
            sex_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Student(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            id_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            name_ = bs;
                            break;
                        }
                        case 24: {
                            int rawValue = input.readEnum();
                            com.jeson.roster.proto.Roster.Student.Sex value = com.jeson.roster.proto.Roster.Student.Sex.valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(3, rawValue);
                            } else {
                                bitField0_ |= 0x00000004;
                                sex_ = rawValue;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
                throw new RuntimeException(
                        new com.google.protobuf.InvalidProtocolBufferException(
                                e.getMessage()).setUnfinishedMessage(this));
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.jeson.roster.proto.Roster.internal_static_Student_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.jeson.roster.proto.Roster.internal_static_Student_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.jeson.roster.proto.Roster.Student.class, com.jeson.roster.proto.Roster.Student.Builder.class);
        }

        public static final com.google.protobuf.Parser<Student> PARSER =
                new com.google.protobuf.AbstractParser<Student>() {
                    public Student parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        try {
                            return new Student(input, extensionRegistry);
                        } catch (RuntimeException e) {
                            if (e.getCause() instanceof
                                    com.google.protobuf.InvalidProtocolBufferException) {
                                throw (com.google.protobuf.InvalidProtocolBufferException)
                                        e.getCause();
                            }
                            throw e;
                        }
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<Student> getParserForType() {
            return PARSER;
        }

        /**
         * Protobuf enum {@code Student.Sex}
         */
        public enum Sex
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>MALE = 0;</code>
             */
            MALE(0, 0),
            /**
             * <code>FEMALE = 1;</code>
             */
            FEMALE(1, 1),;

            /**
             * <code>MALE = 0;</code>
             */
            public static final int MALE_VALUE = 0;
            /**
             * <code>FEMALE = 1;</code>
             */
            public static final int FEMALE_VALUE = 1;


            public final int getNumber() {
                return value;
            }

            public static Sex valueOf(int value) {
                switch (value) {
                    case 0:
                        return MALE;
                    case 1:
                        return FEMALE;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<Sex>
            internalGetValueMap() {
                return internalValueMap;
            }

            private static com.google.protobuf.Internal.EnumLiteMap<Sex>
                    internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
                        public Sex findValueByNumber(int number) {
                            return Sex.valueOf(number);
                        }
                    };

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(index);
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return com.jeson.roster.proto.Roster.Student.getDescriptor().getEnumTypes().get(0);
            }

            private static final Sex[] VALUES = values();

            public static Sex valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            private final int index;
            private final int value;

            private Sex(int index, int value) {
                this.index = index;
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:Student.Sex)
        }

        private int bitField0_;
        public static final int ID_FIELD_NUMBER = 1;
        private int id_;

        /**
         * <code>required int32 id = 1;</code>
         */
        public boolean hasId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        public static final int NAME_FIELD_NUMBER = 2;
        private java.lang.Object name_;

        /**
         * <code>required string name = 2;</code>
         */
        public boolean hasName() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string name = 2;</code>
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    name_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SEX_FIELD_NUMBER = 3;
        private int sex_;

        /**
         * <code>required .Student.Sex sex = 3;</code>
         */
        public boolean hasSex() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required .Student.Sex sex = 3;</code>
         */
        public com.jeson.roster.proto.Roster.Student.Sex getSex() {
            com.jeson.roster.proto.Roster.Student.Sex result = com.jeson.roster.proto.Roster.Student.Sex.valueOf(sex_);
            return result == null ? com.jeson.roster.proto.Roster.Student.Sex.MALE : result;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasSex()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, id_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getNameBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeEnum(3, sex_);
            }
            unknownFields.writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, id_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getNameBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(3, sex_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        public static com.jeson.roster.proto.Roster.Student parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.jeson.roster.proto.Roster.Student parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.jeson.roster.proto.Roster.Student parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.jeson.roster.proto.Roster.Student parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.jeson.roster.proto.Roster.Student parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.jeson.roster.proto.Roster.Student parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.jeson.roster.proto.Roster.Student parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.jeson.roster.proto.Roster.Student parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.jeson.roster.proto.Roster.Student parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.jeson.roster.proto.Roster.Student parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return defaultInstance.toBuilder();
        }

        public static Builder newBuilder(com.jeson.roster.proto.Roster.Student prototype) {
            return defaultInstance.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == defaultInstance
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Student}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Student)
                com.jeson.roster.proto.Roster.StudentOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.jeson.roster.proto.Roster.internal_static_Student_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.jeson.roster.proto.Roster.internal_static_Student_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.jeson.roster.proto.Roster.Student.class, com.jeson.roster.proto.Roster.Student.Builder.class);
            }

            // Construct using com.jeson.roster.proto.Roster.Student.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                id_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                name_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                sex_ = 0;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.jeson.roster.proto.Roster.internal_static_Student_descriptor;
            }

            public com.jeson.roster.proto.Roster.Student getDefaultInstanceForType() {
                return com.jeson.roster.proto.Roster.Student.getDefaultInstance();
            }

            public com.jeson.roster.proto.Roster.Student build() {
                com.jeson.roster.proto.Roster.Student result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.jeson.roster.proto.Roster.Student buildPartial() {
                com.jeson.roster.proto.Roster.Student result = new com.jeson.roster.proto.Roster.Student(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.id_ = id_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.name_ = name_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.sex_ = sex_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.jeson.roster.proto.Roster.Student) {
                    return mergeFrom((com.jeson.roster.proto.Roster.Student) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.jeson.roster.proto.Roster.Student other) {
                if (other == com.jeson.roster.proto.Roster.Student.getDefaultInstance())
                    return this;
                if (other.hasId()) {
                    setId(other.getId());
                }
                if (other.hasName()) {
                    bitField0_ |= 0x00000002;
                    name_ = other.name_;
                    onChanged();
                }
                if (other.hasSex()) {
                    setSex(other.getSex());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                if (!hasId()) {

                    return false;
                }
                if (!hasName()) {

                    return false;
                }
                if (!hasSex()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.jeson.roster.proto.Roster.Student parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.jeson.roster.proto.Roster.Student) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int id_;

            /**
             * <code>required int32 id = 1;</code>
             */
            public boolean hasId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required int32 id = 1;</code>
             */
            public int getId() {
                return id_;
            }

            /**
             * <code>required int32 id = 1;</code>
             */
            public Builder setId(int value) {
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 id = 1;</code>
             */
            public Builder clearId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                id_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object name_ = "";

            /**
             * <code>required string name = 2;</code>
             */
            public boolean hasName() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required string name = 2;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        name_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string name = 2;</code>
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string name = 2;</code>
             */
            public Builder clearName() {
                bitField0_ = (bitField0_ & ~0x00000002);
                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>required string name = 2;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                name_ = value;
                onChanged();
                return this;
            }

            private int sex_ = 0;

            /**
             * <code>required .Student.Sex sex = 3;</code>
             */
            public boolean hasSex() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>required .Student.Sex sex = 3;</code>
             */
            public com.jeson.roster.proto.Roster.Student.Sex getSex() {
                com.jeson.roster.proto.Roster.Student.Sex result = com.jeson.roster.proto.Roster.Student.Sex.valueOf(sex_);
                return result == null ? com.jeson.roster.proto.Roster.Student.Sex.MALE : result;
            }

            /**
             * <code>required .Student.Sex sex = 3;</code>
             */
            public Builder setSex(com.jeson.roster.proto.Roster.Student.Sex value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                sex_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>required .Student.Sex sex = 3;</code>
             */
            public Builder clearSex() {
                bitField0_ = (bitField0_ & ~0x00000004);
                sex_ = 0;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:Student)
        }

        // @@protoc_insertion_point(class_scope:Student)
        private static final com.jeson.roster.proto.Roster.Student defaultInstance;

        static {
            defaultInstance = new com.jeson.roster.proto.Roster.Student();
        }

        public static com.jeson.roster.proto.Roster.Student getDefaultInstance() {
            return defaultInstance;
        }

        public com.jeson.roster.proto.Roster.Student getDefaultInstanceForType() {
            return defaultInstance;
        }

        static {
        }
    }

    public interface StudentRosterOrBuilder extends
            // @@protoc_insertion_point(interface_extends:StudentRoster)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .Student student = 1;</code>
         */
        java.util.List<com.jeson.roster.proto.Roster.Student>
        getStudentList();

        /**
         * <code>repeated .Student student = 1;</code>
         */
        com.jeson.roster.proto.Roster.Student getStudent(int index);

        /**
         * <code>repeated .Student student = 1;</code>
         */
        int getStudentCount();

        /**
         * <code>repeated .Student student = 1;</code>
         */
        java.util.List<? extends com.jeson.roster.proto.Roster.StudentOrBuilder>
        getStudentOrBuilderList();

        /**
         * <code>repeated .Student student = 1;</code>
         */
        com.jeson.roster.proto.Roster.StudentOrBuilder getStudentOrBuilder(
                int index);
    }

    /**
     * Protobuf type {@code StudentRoster}
     */
    public static final class StudentRoster extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:StudentRoster)
            StudentRosterOrBuilder {
        // Use StudentRoster.newBuilder() to construct.
        private StudentRoster(com.google.protobuf.GeneratedMessage.Builder builder) {
            super(builder);
        }

        private StudentRoster() {
            student_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private StudentRoster(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                student_ = new java.util.ArrayList<com.jeson.roster.proto.Roster.Student>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            student_.add(input.readMessage(com.jeson.roster.proto.Roster.Student.PARSER, extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
                throw new RuntimeException(
                        new com.google.protobuf.InvalidProtocolBufferException(
                                e.getMessage()).setUnfinishedMessage(this));
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    student_ = java.util.Collections.unmodifiableList(student_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.jeson.roster.proto.Roster.internal_static_StudentRoster_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.jeson.roster.proto.Roster.internal_static_StudentRoster_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.jeson.roster.proto.Roster.StudentRoster.class, com.jeson.roster.proto.Roster.StudentRoster.Builder.class);
        }

        public static final com.google.protobuf.Parser<StudentRoster> PARSER =
                new com.google.protobuf.AbstractParser<StudentRoster>() {
                    public StudentRoster parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        try {
                            return new StudentRoster(input, extensionRegistry);
                        } catch (RuntimeException e) {
                            if (e.getCause() instanceof
                                    com.google.protobuf.InvalidProtocolBufferException) {
                                throw (com.google.protobuf.InvalidProtocolBufferException)
                                        e.getCause();
                            }
                            throw e;
                        }
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<StudentRoster> getParserForType() {
            return PARSER;
        }

        public static final int STUDENT_FIELD_NUMBER = 1;
        private java.util.List<com.jeson.roster.proto.Roster.Student> student_;

        /**
         * <code>repeated .Student student = 1;</code>
         */
        public java.util.List<com.jeson.roster.proto.Roster.Student> getStudentList() {
            return student_;
        }

        /**
         * <code>repeated .Student student = 1;</code>
         */
        public java.util.List<? extends com.jeson.roster.proto.Roster.StudentOrBuilder>
        getStudentOrBuilderList() {
            return student_;
        }

        /**
         * <code>repeated .Student student = 1;</code>
         */
        public int getStudentCount() {
            return student_.size();
        }

        /**
         * <code>repeated .Student student = 1;</code>
         */
        public com.jeson.roster.proto.Roster.Student getStudent(int index) {
            return student_.get(index);
        }

        /**
         * <code>repeated .Student student = 1;</code>
         */
        public com.jeson.roster.proto.Roster.StudentOrBuilder getStudentOrBuilder(
                int index) {
            return student_.get(index);
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            for (int i = 0; i < getStudentCount(); i++) {
                if (!getStudent(i).isInitialized()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < student_.size(); i++) {
                output.writeMessage(1, student_.get(i));
            }
            unknownFields.writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < student_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, student_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        public static com.jeson.roster.proto.Roster.StudentRoster parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.jeson.roster.proto.Roster.StudentRoster parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.jeson.roster.proto.Roster.StudentRoster parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.jeson.roster.proto.Roster.StudentRoster parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.jeson.roster.proto.Roster.StudentRoster parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.jeson.roster.proto.Roster.StudentRoster parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.jeson.roster.proto.Roster.StudentRoster parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.jeson.roster.proto.Roster.StudentRoster parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.jeson.roster.proto.Roster.StudentRoster parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.jeson.roster.proto.Roster.StudentRoster parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return defaultInstance.toBuilder();
        }

        public static Builder newBuilder(com.jeson.roster.proto.Roster.StudentRoster prototype) {
            return defaultInstance.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == defaultInstance
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code StudentRoster}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:StudentRoster)
                com.jeson.roster.proto.Roster.StudentRosterOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.jeson.roster.proto.Roster.internal_static_StudentRoster_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.jeson.roster.proto.Roster.internal_static_StudentRoster_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.jeson.roster.proto.Roster.StudentRoster.class, com.jeson.roster.proto.Roster.StudentRoster.Builder.class);
            }

            // Construct using com.jeson.roster.proto.Roster.StudentRoster.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getStudentFieldBuilder();
                }
            }

            public Builder clear() {
                super.clear();
                if (studentBuilder_ == null) {
                    student_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    studentBuilder_.clear();
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.jeson.roster.proto.Roster.internal_static_StudentRoster_descriptor;
            }

            public com.jeson.roster.proto.Roster.StudentRoster getDefaultInstanceForType() {
                return com.jeson.roster.proto.Roster.StudentRoster.getDefaultInstance();
            }

            public com.jeson.roster.proto.Roster.StudentRoster build() {
                com.jeson.roster.proto.Roster.StudentRoster result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.jeson.roster.proto.Roster.StudentRoster buildPartial() {
                com.jeson.roster.proto.Roster.StudentRoster result = new com.jeson.roster.proto.Roster.StudentRoster(this);
                int from_bitField0_ = bitField0_;
                if (studentBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        student_ = java.util.Collections.unmodifiableList(student_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.student_ = student_;
                } else {
                    result.student_ = studentBuilder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.jeson.roster.proto.Roster.StudentRoster) {
                    return mergeFrom((com.jeson.roster.proto.Roster.StudentRoster) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.jeson.roster.proto.Roster.StudentRoster other) {
                if (other == com.jeson.roster.proto.Roster.StudentRoster.getDefaultInstance())
                    return this;
                if (studentBuilder_ == null) {
                    if (!other.student_.isEmpty()) {
                        if (student_.isEmpty()) {
                            student_ = other.student_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureStudentIsMutable();
                            student_.addAll(other.student_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.student_.isEmpty()) {
                        if (studentBuilder_.isEmpty()) {
                            studentBuilder_.dispose();
                            studentBuilder_ = null;
                            student_ = other.student_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            studentBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getStudentFieldBuilder() : null;
                        } else {
                            studentBuilder_.addAllMessages(other.student_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                for (int i = 0; i < getStudentCount(); i++) {
                    if (!getStudent(i).isInitialized()) {

                        return false;
                    }
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.jeson.roster.proto.Roster.StudentRoster parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.jeson.roster.proto.Roster.StudentRoster) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.util.List<com.jeson.roster.proto.Roster.Student> student_ =
                    java.util.Collections.emptyList();

            private void ensureStudentIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    student_ = new java.util.ArrayList<com.jeson.roster.proto.Roster.Student>(student_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    com.jeson.roster.proto.Roster.Student, com.jeson.roster.proto.Roster.Student.Builder, com.jeson.roster.proto.Roster.StudentOrBuilder> studentBuilder_;

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public java.util.List<com.jeson.roster.proto.Roster.Student> getStudentList() {
                if (studentBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(student_);
                } else {
                    return studentBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public int getStudentCount() {
                if (studentBuilder_ == null) {
                    return student_.size();
                } else {
                    return studentBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public com.jeson.roster.proto.Roster.Student getStudent(int index) {
                if (studentBuilder_ == null) {
                    return student_.get(index);
                } else {
                    return studentBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public Builder setStudent(
                    int index, com.jeson.roster.proto.Roster.Student value) {
                if (studentBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureStudentIsMutable();
                    student_.set(index, value);
                    onChanged();
                } else {
                    studentBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public Builder setStudent(
                    int index, com.jeson.roster.proto.Roster.Student.Builder builderForValue) {
                if (studentBuilder_ == null) {
                    ensureStudentIsMutable();
                    student_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    studentBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public Builder addStudent(com.jeson.roster.proto.Roster.Student value) {
                if (studentBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureStudentIsMutable();
                    student_.add(value);
                    onChanged();
                } else {
                    studentBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public Builder addStudent(
                    int index, com.jeson.roster.proto.Roster.Student value) {
                if (studentBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureStudentIsMutable();
                    student_.add(index, value);
                    onChanged();
                } else {
                    studentBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public Builder addStudent(
                    com.jeson.roster.proto.Roster.Student.Builder builderForValue) {
                if (studentBuilder_ == null) {
                    ensureStudentIsMutable();
                    student_.add(builderForValue.build());
                    onChanged();
                } else {
                    studentBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public Builder addStudent(
                    int index, com.jeson.roster.proto.Roster.Student.Builder builderForValue) {
                if (studentBuilder_ == null) {
                    ensureStudentIsMutable();
                    student_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    studentBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public Builder addAllStudent(
                    java.lang.Iterable<? extends com.jeson.roster.proto.Roster.Student> values) {
                if (studentBuilder_ == null) {
                    ensureStudentIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, student_);
                    onChanged();
                } else {
                    studentBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public Builder clearStudent() {
                if (studentBuilder_ == null) {
                    student_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    studentBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public Builder removeStudent(int index) {
                if (studentBuilder_ == null) {
                    ensureStudentIsMutable();
                    student_.remove(index);
                    onChanged();
                } else {
                    studentBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public com.jeson.roster.proto.Roster.Student.Builder getStudentBuilder(
                    int index) {
                return getStudentFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public com.jeson.roster.proto.Roster.StudentOrBuilder getStudentOrBuilder(
                    int index) {
                if (studentBuilder_ == null) {
                    return student_.get(index);
                } else {
                    return studentBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public java.util.List<? extends com.jeson.roster.proto.Roster.StudentOrBuilder>
            getStudentOrBuilderList() {
                if (studentBuilder_ != null) {
                    return studentBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(student_);
                }
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public com.jeson.roster.proto.Roster.Student.Builder addStudentBuilder() {
                return getStudentFieldBuilder().addBuilder(
                        com.jeson.roster.proto.Roster.Student.getDefaultInstance());
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public com.jeson.roster.proto.Roster.Student.Builder addStudentBuilder(
                    int index) {
                return getStudentFieldBuilder().addBuilder(
                        index, com.jeson.roster.proto.Roster.Student.getDefaultInstance());
            }

            /**
             * <code>repeated .Student student = 1;</code>
             */
            public java.util.List<com.jeson.roster.proto.Roster.Student.Builder>
            getStudentBuilderList() {
                return getStudentFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    com.jeson.roster.proto.Roster.Student, com.jeson.roster.proto.Roster.Student.Builder, com.jeson.roster.proto.Roster.StudentOrBuilder>
            getStudentFieldBuilder() {
                if (studentBuilder_ == null) {
                    studentBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            com.jeson.roster.proto.Roster.Student, com.jeson.roster.proto.Roster.Student.Builder, com.jeson.roster.proto.Roster.StudentOrBuilder>(
                            student_,
                            ((bitField0_ & 0x00000001) == 0x00000001),
                            getParentForChildren(),
                            isClean());
                    student_ = null;
                }
                return studentBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:StudentRoster)
        }

        // @@protoc_insertion_point(class_scope:StudentRoster)
        private static final com.jeson.roster.proto.Roster.StudentRoster defaultInstance;

        static {
            defaultInstance = new com.jeson.roster.proto.Roster.StudentRoster();
        }

        public static com.jeson.roster.proto.Roster.StudentRoster getDefaultInstance() {
            return defaultInstance;
        }

        public com.jeson.roster.proto.Roster.StudentRoster getDefaultInstanceForType() {
            return defaultInstance;
        }

        static {
        }
    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Student_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Student_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_StudentRoster_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_StudentRoster_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\014Roster.proto\"[\n\007Student\022\n\n\002id\030\001 \002(\005\022\014\n" +
                        "\004name\030\002 \002(\t\022\031\n\003sex\030\003 \002(\0162\014.Student.Sex\"\033" +
                        "\n\003Sex\022\010\n\004MALE\020\000\022\n\n\006FEMALE\020\001\"*\n\rStudentRo" +
                        "ster\022\031\n\007student\030\001 \003(\0132\010.StudentB \n\026com.j" +
                        "eson.roster.protoB\006Roster"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_Student_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Student_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_Student_descriptor,
                new java.lang.String[]{"Id", "Name", "Sex",});
        internal_static_StudentRoster_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_StudentRoster_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_StudentRoster_descriptor,
                new java.lang.String[]{"Student",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
